# -*- coding: utf-8 -*-
"""BoilerWater.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_vrTm1TftnLQqrz2jyE2Zc53ZK8sPh4
"""

df = pd.read_csv('Q&A Boiler Chemistry.csv', encoding='latin1')
print(df.columns)

import pandas as pd # Import the pandas library and alias it as 'pd'
import streamlit
import transformers

!pip install chardet

import chardet

with open('Q&A Boiler Chemistry.csv', 'rb') as file:
    result = chardet.detect(file.read())
    print(result)

df = pd.read_csv('Q&A Boiler Chemistry.csv', encoding=result['encoding'])

df = pd.read_csv('Q&A Boiler Chemistry.csv', encoding='latin1')
print(df.head())

with open('Q&A Boiler Chemistry.csv', 'r', encoding='utf-8', errors='replace') as file:
    content = file.read()

with open('Q&A_Cleaned.csv', 'w', encoding='utf-8') as file:
    file.write(content)

df = pd.read_csv('Q&A_Cleaned.csv')
print(df.head())

try:
    # Attempt to read with UTF-8
    df = pd.read_csv('Q&A Boiler Chemistry.csv', encoding='utf-8')
except UnicodeDecodeError:
    # If UTF-8 fails, try a fallback encoding
    df = pd.read_csv('Q&A Boiler Chemistry.csv', encoding='latin1')
except Exception as e:
    print("An error occurred:", e)

print(df.head())

!pip install chardet

import chardet

with open('Q&A Boiler Chemistry.csv', 'rb') as file:
    result = chardet.detect(file.read(10000))  # Analyze the first 10,000 bytes
    print(result)  # This will print the detected encoding

df = pd.read_csv('Q&A Boiler Chemistry.csv', encoding='ISO-8859-1', delimiter=';')
print(df.head())

with open('Q&A Boiler Chemistry.csv', 'r', encoding='utf-8', errors='ignore') as file:
    content = file.read()

# Save the processed content
with open('Q&A_Boiler_Chemistry_Cleaned.csv', 'w', encoding='utf-8') as file:
    file.write(content)

# Now load the cleaned file
df = pd.read_csv('Q&A_Boiler_Chemistry_Cleaned.csv', delimiter=';')
print(df.head())

with open('Q&A Boiler Chemistry.csv', 'r', encoding='ISO-8859-1', errors='ignore') as file:
    line = file.readline()
    print(line)  # Check the first line

df = pd.read_csv('Q&A Boiler Chemistry.csv', encoding='ISO-8859-1', delimiter=',')  # Change ',' to your delimiter
print(df.head())

import chardet

with open('Q&A Boiler Chemistry.csv', 'rb') as file:
    result = chardet.detect(file.read(10000))  # Analyze the first 10,000 bytes
    print(result)

df = pd.read_csv('Q&A Boiler Chemistry.csv', encoding=result['encoding'], delimiter=',')  # Adjust delimiter
print(df.head())

import pandas as pd

# Replace 'path/to/your/file/' with the actual path
file_path = '/content/Q&A_Cleaned.csv'
df = pd.read_csv(file_path, delimiter=',')
print(df.head())

import streamlit as st
from transformers import pipeline

# Load the Q&A model
qa_model = pipeline("question-answering", model="distilbert-base-cased", tokenizer="distilbert-base-cased")

# Streamlit App
st.title("Boiler Chemistry Q&A Chatbot")
st.write("Ask me anything about boiler chemistry!")

# User input
user_question = st.text_input("Your Question:")
if user_question:
    # Example context
    context = """
    Boiler chemistry refers to the study of chemical processes and properties
    in boilers, including water treatment, scaling, and corrosion control.
    """
    response = qa_model(question=user_question, context=context)
    st.write("Answer:", response['answer'])

import pandas as pd
import streamlit
import transformers

pip install pandas streamlit transformers