# -*- coding: utf-8 -*-
"""BoilerWater.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_vrTm1TftnLQqrz2jyE2Zc53ZK8sPh4
"""

from google.colab import drive
drive.mount('/content/gdrive')

file_path = '/content/drive/My Drive/path/to/your/boiler_chemistry_data.txt'

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/path/to/your/boiler_chemistry_data.txt'

try:
    with open(file_path, 'r') as file:
        data = file.read()
    print(data)
except FileNotFoundError:
    print("The file was not found. Please check the path and try again.")

!pip install nltk

import nltk
from nltk.chat.util import Chat, reflections

# Download the required NLTK data (run only if needed)
nltk.download('punkt')

# Define patterns and responses
patterns = [
    (r"hi|hello|hey", ["Hello! How can I help you?", "Hi there! What can I do for you?", "Hello!"]),
    (r"how are you?", ["I'm doing well, thank you! How can I assist you today?"]),
    (r"what is your name?", ["I am your helpful chatbot. What's your name?"]),
    (r"my name is (.*)", ["Nice to meet you, %1! How can I help you?"]),
    (r"what do you do?", ["I am here to assist you with any questions you might have."]),
    (r"quit", ["Goodbye! Have a great day!"])
]

# Define reflections (adjustments based on user inputs)
reflections = {
    "i am": "you are",
    "i was": "you were",
    "i": "you",
    "i'd": "you would",
    "i've": "you have",
    "i'll": "you will",
    "my": "your",
    "you are": "I am",
    "you were": "I was",
    "you've": "I have",
    "you'll": "I will",
    "your": "my",
    "yours": "mine",
    "you": "me",
    "me": "you"
}

# Create the chatbot
chatbot = Chat(patterns, reflections)

file_path = '/content/drive/My Drive/[correct_file_path_here]/boiler_chemistry_data.txt'

# Attempt to read the file content
try:
    with open(file_path, 'r') as file:
        boiler_data = file.read()
    print("File loaded successfully!")
except FileNotFoundError:
    print("Error: File not found. Please check the file path.")

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/[boiler_chemistry_data.txt]/'

# Sample Q&A pairs based on your data
qa_pairs = {
    "Why is boiler chemistry essential for boiler operations?": "Boiler chemistry is vital to ensure efficient and safe operation by preventing issues like corrosion, scaling, and excessive buildup of impurities, which can lead to costly repairs and downtime.",
    "What types of water are typically used in boiler systems?": "The main types of water used are Raw Water, Make-Up Water, Feed Water, and Condensate Return. Each serves a unique purpose, from replacing water losses to maintaining water quality in the system.",
    "What is the role of 'Make-Up Water' in a boiler system?": "Make-Up Water is added to replace water lost due to steam production and leaks, ensuring the boiler has a consistent water level and proper functionality.",
    "What does 'water softening' do in boiler treatment?": "Water softening reduces hardness caused by minerals like calcium and magnesium, which can cause scale buildup. This helps to maintain heat transfer efficiency and reduce wear on the boiler.",
    "Why is deaeration necessary for boiler water?": "Deaeration removes dissolved gases, such as oxygen and carbon dioxide, that can lead to corrosion of the boilers metal parts. This process helps extend the life of the boiler system.",
    "What are the optimal pH levels for boiler water, and why are they important?": "Boiler water should have a pH between 10 and 12 to prevent corrosion. Maintaining this range minimizes the risk of acidic or alkaline corrosion in the system.",
    "How does 'Total Dissolved Solids' (TDS) affect boiler performance?": "High TDS can lead to scaling and foaming, which reduce efficiency and cause overheating. Regular blowdowns help control TDS levels within safe limits, ensuring smoother operation.",
    "Why is monitoring dissolved oxygen important in boiler water?": "Dissolved oxygen should be kept below 7 ppb to avoid corrosion. Excessive oxygen in the boiler can corrode metal surfaces, which can lead to system failures.",
    "What are some best practices for maintaining good boiler water chemistry?": "Best practices include regular testing and monitoring, routine blowdowns to remove dissolved solids, and proper chemical dosing to maintain balanced pH and reduce impurities.",
    "How does proper boiler chemistry help improve efficiency?": "Maintaining proper chemistry prevents scale buildup and corrosion, allowing for better heat transfer, lower fuel consumption, and reduced maintenance costs, all of which enhance overall efficiency."
}

def chatbot_response(user_question):
    # Check if the user question is in the dictionary
    response = qa_pairs.get(user_question)
    if response:
        return response
    else:
        return "I'm sorry, I don't have an answer for that question. Please ask about boiler chemistry."

# Define the boiler chemistry data
qa_data = {
    "Why is boiler chemistry essential for boiler operations?": "Boiler chemistry is vital to ensure efficient and safe operation by preventing issues like corrosion, scaling, and excessive buildup of impurities, which can lead to costly repairs and downtime.",
    "What types of water are typically used in boiler systems?": "The main types of water used are Raw Water, Make-Up Water, Feed Water, and Condensate Return. Each serves a unique purpose, from replacing water losses to maintaining water quality in the system.",
    "What is the role of 'Make-Up Water' in a boiler system?": "Make-Up Water is added to replace water lost due to steam production and leaks, ensuring the boiler has a consistent water level and proper functionality.",
    "What does 'water softening' do in boiler treatment?": "Water softening reduces hardness caused by minerals like calcium and magnesium, which can cause scale buildup. This helps to maintain heat transfer efficiency and reduce wear on the boiler.",
    "Why is deaeration necessary for boiler water?": "Deaeration removes dissolved gases, such as oxygen and carbon dioxide, that can lead to corrosion of the boiler's metal parts. This process helps extend the life of the boiler system.",
    "What are the optimal pH levels for boiler water, and why are they important?": "Boiler water should have a pH between 10 and 12 to prevent corrosion. Maintaining this range minimizes the risk of acidic or alkaline corrosion in the system.",
    "How does 'Total Dissolved Solids' (TDS) affect boiler performance?": "High TDS can lead to scaling and foaming, which reduce efficiency and cause overheating. Regular blowdowns help control TDS levels within safe limits, ensuring smoother operation.",
    "Why is monitoring dissolved oxygen important in boiler water?": "Dissolved oxygen should be kept below 7 ppb to avoid corrosion. Excessive oxygen in the boiler can corrode metal surfaces, which can lead to system failures.",
    "What are some best practices for maintaining good boiler water chemistry?": "Best practices include regular testing and monitoring, routine blowdowns to remove dissolved solids, and proper chemical dosing to maintain balanced pH and reduce impurities.",
    "How does proper boiler chemistry help improve efficiency?": "Maintaining proper chemistry prevents scale buildup and corrosion, allowing for better heat transfer, lower fuel consumption, and reduced maintenance costs, all of which enhance overall efficiency."
}

# Define the chatbot's response function
def chatbot_response(user_input):
    # Check if the user input matches a predefined question
    response = qa_data.get(user_input)

    if response:
        return response  # Return the matching answer
    else:
        return "I'm sorry, I can only answer specific questions about boiler chemistry."

# Chatbot interaction loop
print("Chatbot: Welcome! Ask me any questions about boiler chemistry. Type 'quit' to end the conversation.")

while True:
    # Ask the user for input
    user_input = input("You: ")

    # Check if the user wants to quit
    if user_input.lower() == "quit":
        print("Chatbot: Goodbye! Feel free to ask about boiler chemistry anytime.")
        break

    # Get the chatbot's response
    response = chatbot_response(user_input)

    # Print the chatbot's response
    print("Chatbot:", response)

pip install streamlit

import streamlit as st
import random

# Predefined responses for the chatbot
boiler_chemistry_data = {
    "what is boiler chemistry": "Boiler chemistry is essential for maintaining efficient and safe boiler operations...",
    "types of water used in boilers": "The main types of water used are Raw Water, Make-Up Water, Feed Water, and Condensate Return...",
    "role of make-up water": "Make-Up Water is added to replace water lost due to steam production and leaks...",
    # Add more predefined data as needed
}

# Function to get chatbot response
def chatbot_response(user_input):
    user_input = user_input.lower()
    if user_input in boiler_chemistry_data:
        return boiler_chemistry_data[user_input]
    else:
        return "Sorry, I don't have an answer for that. Please ask something about boiler chemistry."

# Streamlit UI
st.title("Boiler Chemistry Chatbot")

st.write("Ask me any questions about boiler chemistry. Type 'quit' to end the conversation.")

# Chat loop
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

user_input = st.text_input("You:", "")

if user_input:
    if user_input.lower() == "quit":
        st.session_state.chat_history.append(("You", "quit"))
        st.session_state.chat_history.append(("Chatbot", "Goodbye! Feel free to ask about boiler chemistry anytime."))
    else:
        response = chatbot_response(user_input)
        st.session_state.chat_history.append(("You", user_input))
        st.session_state.chat_history.append(("Chatbot", response))

# Display chat history
for chat in st.session_state.chat_history:
    st.write(f"{chat[0]}: {chat[1]}")